# Generated by Django 2.2.4 on 2022-10-04 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0002_auto_20221004_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
